### ISSUE TITLE
Stop tracking application.properties

### ISSUE THREAD

**Issue by wchrismonty** [ayush2k/securbank#38]
The `application.properties` file is where Securbank retrieves configurations from when connecting to the database among other things. These values--especially the URL, username, and password--vary depending on the environment. Hence, we need to stop tracking the `application.properties` file in version control, i.e. add it to `.gitignore`.

In addition, there should be a `sample.properties` file that serves as a guideline to help create the real `application.properties` file for the current environment.

**Comment by ayush2k** [comment]
@wchrismontgomery 
Except for DB configuration, all the information in application.properties contains application specific information. Also, if we remove it, our build will fail on git.

**Comment by wchrismonty** [comment]
I just learned that settings in `application.properties` can be overridden in a different `application.properties` file in a `/config` subdirectory of the directory containing the original `application.properties`. I'm closing this issue.
